services:
  app:
    build: .
    command: npm run dev #should use nodemon when changes found then restart server for realtime update from local machine to docker container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
  client:
    build: ./client
    command: npm run start #should use nodemon when changes found then restart server
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
    restart: always
  nginx:
    image: nginx:1.25-alpine3.17
    container_name: nginx-container
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
    restart: always
    depends_on:
      - app
      - client
